# Generated by Django 4.2.7 on 2023-11-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayArtItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('art_type', models.CharField(choices=[('CEMENT', 'Cement'), ('PHOTOGRAPHY', 'Photography'), ('EMBROIDERY', 'Embroidery'), ('POTTERY', 'Pottery'), ('USER_ART', 'User Art')], max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreArtItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('art_type', models.CharField(choices=[('CEMENT', 'Cement'), ('PHOTOGRAPHY', 'Photography'), ('EMBROIDERY', 'Embroidery'), ('POTTERY', 'Pottery'), ('USER_ART', 'User Art')], max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserArtItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('art_type', models.CharField(choices=[('CEMENT', 'Cement'), ('PHOTOGRAPHY', 'Photography'), ('EMBROIDERY', 'Embroidery'), ('POTTERY', 'Pottery'), ('USER_ART', 'User Art')], max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('token', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
